services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=disable
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.planfact.rule=Host(`planfact.astralswag.ru`)"
      - "traefik.http.routers.planfact.entrypoints=websecure"
      - "traefik.http.routers.planfact.tls=true"
      - "traefik.http.services.planfact.loadbalancer.server.port=8080"
      # Basic Auth middleware
      - "traefik.http.routers.planfact.middlewares=planfact-auth"
      - "traefik.http.middlewares.planfact-auth.basicauth.users=${HTTP_BASIC_AUTH}"
      - "traefik.http.middlewares.planfact-auth.basicauth.removeheader=true"
    networks:
      - traefik-net
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
      - ./init-tables.sh:/docker-entrypoint-initdb.d/init-tables.sh
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: ["postgres", "-c", "max_connections=1000"]
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  traefik-net:
    external: true
  app-network:
    driver: bridge