version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.planfact.rule=Host(`planfact.example.com`)"
      - "traefik.http.routers.planfact.entrypoints=https"
      - "traefik.http.routers.planfact.tls.certResolver=acme"
      # Basic Auth middleware
      - "traefik.http.routers.planfact.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${HTTP_BASIC_AUTH}"
      - "traefik.http.middlewares.auth.basicauth.removeheader=true"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./astralswag.db:/app/astralswag.db