services:
  app:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.planfact.rule=Host(`planfact.astralswag.ru`)"
      - "traefik.http.routers.planfact.entrypoints=websecure"
      - "traefik.http.routers.planfact.tls=true"
      - "traefik.http.services.planfact.loadbalancer.server.port=8080"
      # Basic Auth middleware
      - "traefik.http.routers.planfact.middlewares=planfact-auth"
      - "traefik.http.middlewares.planfact-auth.basicauth.users=${HTTP_BASIC_AUTH}"
      - "traefik.http.middlewares.planfact-auth.basicauth.removeheader=true"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true